spring:
  datasource:
    hikari-local:
      connection-init-sql: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/webtoon?serverTimezone=Asia/Seoul 
      username: webtoon
      password: webtoon
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
logging:
  level:
    root: warn
    kongkk: warn
data:
  base-folders:
    - folder:
      path: H:/hitomi_downloader_GUI
      remote: null
    - folder:
      path: contents/hitomi_downloader_GUI
      remote: jongki99
    - folder:
      path: V:/hitomi_downloader_GUI
      remote: null
env:
  swagger:
    host: localhost:8181
